#
# https://www.digitalocean.com/community/tutorials/how-to-install-ruby-on-rails-with-rbenv-on-ubuntu-16-04
#
---
- name: "Install packages required by Bundler / Rails."
  apt: 
    name={{ item }} state=latest
  with_items:
    - gcc
    - autoconf
    - bison
    - build-essential
    - libssl-dev
    - libyaml-dev
    - libreadline6-dev
    - zlib1g-dev
    - libncurses5-dev
    - libffi-dev
    - libgdbm3
    - libgdbm-dev
    - sqlite3
    - libsqlite3-dev
    - libpq-dev
  become: yes