# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9b4aba3f76f6b3cd31da75b91a9757c9c4d1dd08c7f22da34f124f94231ac490cccd7aa0c497a2bd7e3a4e29245555c7faff1d9f4f9164715484913a3cd9abe0

test:
  secret_key_base: 9c4600402a1975cbb01edbdadbcab334f3999ea5f345dbb8f900fb67b6a25e923dd7acf118dabc6f04c13a275497ac4312401f9fad3bf85bd1564368182b7c40

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
